models/News.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $content
 * @property integer $created_at
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'title', 'content', 'created_at'], 'required'],
            [['user_id', 'created_at'], 'integer'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'title' => Yii::t('app', 'Title'),
            'content' => Yii::t('app', 'Content'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    public function getShortDescription()
    {
        return mb_substr($this->content, 0, 100);
    }

    public function getCreatedDate()
    {
        return date('d.m.Y', $this->created_at);
    }
}

controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\News;
use app\services\news\NewsBuilder;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    const DEFAULT_PAGE_LIMIT = 20;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['?', '@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['view'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['manager'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex($limit = self::DEFAULT_PAGE_LIMIT)
    {
        $limit = intval($limit);

        $dataProvider = new ActiveDataProvider([
            'query' => News::find()->orderBy('[[created_at]] DESC'),
            'pagination' => [
                'pageSize' => $limit,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'limit' => $limit,
        ]);
    }

    /**
     * Displays a single News model.
     * @param  integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new News();
        $request = \Yii::$app->request;
        $builder = $this->getBuilder($model);

        if ($request->isPost && $builder->save($request)) {
            return $this->redirect([
                'view',
                'id' => $builder->getModel()->id,
            ]);
        }

        return $this->render('create', [
            'model' => $builder->getModel(),
        ]);
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $request = \Yii::$app->request;
        $builder = $this->getBuilder($model);

        if ($request->isPost && $builder->save($request)) {
            return $this->redirect([
                'view',
                'id' => $builder->getModel()->id,
            ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param  integer               $id
     * @return News                  the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function getBuilder($model = null)
    {
        $user = \Yii::$app->user->identity;

        return new NewsBuilder($user, $model);
    }
}

views/news/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\News */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/news/_item.php
<?php
use yii\helpers\Html;
?>
<div class="news-item">
	<h2><?= $model->title ?></h2>
	<p class="text-muted"><?= $model->createdDate ?></p>
	<p><?= $model->shortDescription ?></p>
	<?php if (\Yii::$app->user->can('viewNews')): ?>
		<p><?= Html::a('Read More...', ['view', 'id' => $model->id]) ?></p>
	<?php else: ?>
		<p class="text-muted">Sign up to obtain full view access</p>
	<?php endif; ?>
</div>

views/news/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = Yii::t('app', 'Create News');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/news/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\widgets\ListView;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'News');
$this->params['breadcrumbs'][] = $this->title;

if (\Yii::$app->user->can('manageNews')) {
    $this->params['pageControls'][] = [
        'label' => Yii::t('app', 'Create News'),
        'url' => ['create'],
        'options' => [
                'class' => 'btn btn-success',
            ],
    ];
}

?>
<div class="news-index">

	<h1><?= Html::encode($this->title) ?></h1>

	<?php Pjax::begin(); ?>
		<p>
			<ul class="list list-inline">
				<li>News per page:</li>
				<?php foreach ([100, 50, 20] as $limitSize): ?>
					<li <?= $limit == $limitSize ? 'class="active"' : ''?>>
						<?= Html::a($limitSize, ['news/index', 'limit' => $limitSize]) ?>
					</li>
				<?php endforeach; ?>
			</ul>
	    </p>

	    <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_item',
        ]); ?>
	<?php Pjax::end(); ?>
</div>

views/news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'News',
]) . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="news-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/news/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'News'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['pageControls'][] = [
        'label' => Yii::t('app', 'Update'),
        'url' => ['update', 'id' => $model->id],
        'options' => [
            'class' => 'btn btn-primary',
        ],

    ];

$this->params['pageControls'][] = [
        'label' => Yii::t('app', 'Delete'),
        'url' => ['delete', 'id' => $model->id],
        'options' => [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ],
    ];
?>

<div class="news-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <p class="text-muted"><?= $model->createdDate ?></p>
    <p><?= $model->content ?></p>

</div>